const cell = {
  rowNum: 'A',
  id: 'B',
  status: 'D',
  category: 'F',
  name: 'G',
  furigana: 'H',
  gender: 'J',
  age: 'K',
  birthday: 'L',
  postCode: 'M',
  address1: 'N',
  address2: 'O',
  address3: 'P',
  address4: 'Q',
  address5: 'R',
  phoneNumber: 'S',
  email: 'T',
};
